from typing import Protocol


class StreamReaderLike(Protocol):
    async def read(self, n: int) -> bytes: ...

    async def readexactly(self, n: int) -> bytes: ...


class StreamWriterLike(Protocol):
    def write(self, data: bytes) -> None: ...

    async def drain(self) -> None: ...

    def close(self) -> None: ...
