from typing import Protocol


class StreamReaderLike(Protocol):
    def read_blocking(self, n: int) -> bytes: ...

    def readexactly_blocking(self, n: int) -> bytes: ...


class StreamWriterLike(Protocol):
    def write(self, data: bytes) -> None: ...

    def drain_blocking(self) -> None: ...

    def close(self) -> None: ...
